### ISSUE TITLE
page can't be found for quickly generate an Azure IoT application.

### ISSUE THREAD

**Issue by czgtest** [microsoft/vscode-azure-iot-tools#10]
1.In Command Palette: Run `Azure IoT Tools: Show Welcome Page` 
2. click the link of quickly generate an Azure IoT application.
page can not be found

![image](https://user-images.githubusercontent.com/35018765/57597490-2b0d4900-7582-11e9-8944-c427578ce75b.png)

**Comment by formulahendry** [comment]
Fixed. Please help verify.
