### ISSUE TITLE
Different content area width between tabs

### ISSUE THREAD

**Issue by Sneezry** [Microsoft/vscode-azure-iot-tools#3]
![tab](https://user-images.githubusercontent.com/1621293/51820099-b33b4b80-230f-11e9-8400-5425f414e1e1.gif)

**Comment by SLdragon** [comment]
@Sneezry , thanks for your suggestions, I update the code to fix this issue: https://github.com/Microsoft/vscode-azure-iot-tools/pull/2/commits/fac87926389faf1805fbfeaa637e72ada6ac1a4e
