### ISSUE TITLE
“Azure IoT Tools” extension not display in VSCode menu after install.

### ISSUE THREAD

**Issue by czgtest** [microsoft/vscode-azure-iot-tools#9]
OS: windows10
Azure IoT tools :0.0.3-rc

step:
1.open VS Code , here only Azure Account  has already installed
1.install Azure IoT tools from VSIX
2.After installing successfully,  check “Azure IoT Tools”, “Azure IoT Toolkit”, “Azure IoT Device Workbench” and “Azure IoT Edge” **are not display** in VS Code 
and there is no message to reminder user to reload VS Code 

![image](https://user-images.githubusercontent.com/35018765/57594973-31e18f00-7575-11e9-83d3-910b6b017fb0.png)

**Comment by formulahendry** [comment]
VS Code issue
